### ISSUE TITLE
Bad image taken

### ISSUE THREAD

**Issue by filipkrystl** [nstudio/nativescript-camera-plus#114] opened 2020-02-06 11:26 UTC
Hi all, I needed a way to preview and take pictures in my application. I was trying this plugin and I was getting weird images so I tried also the demo app and I am getting the same results. 

In the preview of the camera, it all looks fine. But whenever I take the picture it is totally unreadable. If I start and stop recording, it is also fine. 

Here is how it looks like in the app:
![Screenshot_2020-02-06-12-03-35](https://user-images.githubusercontent.com/17198649/73932101-e24cab80-48d9-11ea-8760-c80cd51ae523.png)

This is the saved image:
![PIC_20200206120308](https://user-images.githubusercontent.com/17198649/73932146-001a1080-48da-11ea-8796-86ef824e4fea.jpg)

- CLI: 6.3.3

### Please, tell us how to recreate the issue in as much detail as possible. 

Download demo app. Runing on device Huawei M2-A01L

**Comment by rhurup** [comment] 2020-06-25 12:30
Have the same issue here ... The issue is not on all android phones.

**Comment by vicmasa** [comment] 2020-08-06 16:32
Hi, I have the same error on my Motorola device  
Model: Moto C 
Android 7

**Comment by frozenmaiden** [comment] 2020-08-12 01:37
Hi,
I have same issue here
Test Phone: Xiaomi Redmi Note 4, Vivo, and Sony Experia

**Comment by triniwiz** [comment] 2020-12-01 16:47
Should be fixed with the latest release `3.1.x` feel free to reopen

**Closed by triniwiz** 2020-12-01 16:47 UTC
